### ISSUE TITLE
Unable to start bin/www

### ISSUE THREAD

**Issue by KeironO** [bio-ontology-research-group/aberowl-meta#1]
Whenever I attempt to start bin/www, I'm getting a TypeError after the latest release of aberowl-web.

``` bash
➜  aberowl-web git:(c1df353) ✗ bin/www 
express-session deprecated undefined resave option; provide resave option app.js:46:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:46:9

TypeError: Cannot set property 'statusCode' of undefined
    at Request._callback (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/routes/index.js:12:30)
    at self.callback (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.onRequestError (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/node_modules/request/request.js:861:8)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1547:9)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
```

**Comment by debuos512** [comment]
Change app.js#53 to a valid path to AberOWL-server API. If you did the
Apache proxy it should probably be 'http://localhost/service/api/'

On 20 July 2015 at 09:26, KeironO notifications@github.com wrote:

> Whenever I attempt to start bin/www, I'm getting a TypeError after the
> latest release of aberowl-web.
> 
> ``bash
> ➜ aberowl-web git:(c1df353) ✗ bin/www
> express-session deprecated undefined resave option; provide resave option
> app.js:46:9
> express-session deprecated undefined saveUninitialized option; provide
> saveUninitialized option app.js:46:9
> 
> TypeError: Cannot set property 'statusCode' of undefined
> at Request._callback
> (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/routes/index.js:12:30)
> at self.callback
> (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/node_modules/request/request.js:198:22)
> at Request.EventEmitter.emit (events.js:95:17)
> at Request.onRequestError
> (/home/keiron/Documents/Projects/aberowl-meta/aberowl-web/node_modules/request/request.js:861:8)
> at ClientRequest.EventEmitter.emit (events.js:95:17)
> at Socket.socketErrorListener (http.js:1547:9)
> at Socket.EventEmitter.emit (events.js:95:17)
> at net.js:441:14
> at process._tickCallback (node.js:415:13)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bio-ontology-research-group/aberowl-meta/issues/1.

## 

Luke Slater
:O)

**Comment by debuos512** [comment]
Should probably just change it to that by default, given that's our suggested route in the README

**Comment by KeironO** [comment]
Still having issues.

**Comment by KeironO** [comment]
I have followed the README religiously, and am still having the exact same issues.

Can I suggest that you re-install it on a fresh system, and see whether you have the same problems? @MiguelAngelRG had these same issues but forgot how he fixed them.

**Comment by KeironO** [comment]
How @MiguelAngelRG  fixed it:
1. Cloned the (aberowl-orepo)[https://github.com/bio-ontology-research-group/aberowl-orepo] repository into aberowl-meta
2. Removed aberowl-web and renamed orepo to web.
3. Installed all of the npm modules.
4. Configured app.js to run off localhost

Thanks.

**Comment by debuos512** [comment]
That doesn't really make sense as a solution, but I'm glad it works. 

@KeironO @MiguelAngelRG I will be removing the tracking submodules and implementing install script just straight cloning the most recent version this evening or tomorrow.
