### ISSUE TITLE
Confusion in the configuration

### ISSUE THREAD

**Issue by MiguelAngelRG** [bio-ontology-research-group/aberowl-meta#2]
Hi guys, 

I am a little confused about the configuration of AberOWL. I am running the front-end (aberowl-web) and back-end (aberowl-server) in my own computer (localhost). The problem is that the frontend is not able to communicate with the backend through the API without writing the whole path. For instance, in order to execute the script getStats.groovy is necessary to write: "http:localhost:9222/api/service/getStats.groovy" 
Because with the current configuration does not work: "/service/api/service/getStats.groovy"
I think that I made some mistake during the installation of AberOWL because in otherwise I should have to replace "http://localhost:9222" in all javascript files (sparql.js, tree.js, quick search.js,query.js,help, browse.js) and I suppose that this is not the correct solution.

**Comment by debuos512** [comment]
Did you manage to find anything in the apache error log?
