### ISSUE TITLE
After installing as per Readme (20.11.2015): MultipleCompilationErrorsException

### ISSUE THREAD

**Issue by Zsar** [bio-ontology-research-group/aberowl-meta#3]
On readme entry "Running", first paragraph: `groovy AberOWLServer.groovy`

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/zsar/aberowl-meta/aberowl-server/src/RequestManager.groovy: 281: unable to resolve class AberOWLSyntaxRendererImpl
@ line 281, column 29.
    def manSyntaxRenderer = new AberOWLRendererImpl()
                            ^
1 error
```

The system is a fresh Ubuntu 15.10 installed from iso and upgraded thereafter.
All installation steps have been done today.

Note that I had to replace the dependency "node" with "nodejs-legacy", as that package does no longer exist. While executing the second installation step "./install", nPM generated warnings regarding the node minor version (is .25, should have been >=.32), but I doubt this is related.

... Any advice? Reproducible? Any _hidden_ dependencies I might have missed?
Can I do anything to further diagnose this fault?

**Comment by leechuck** [comment]
Sorry, this is my fault, I forgot to commit the latest changes. There were two files missing for rendering Manchester OWL Syntax, they are added now.
