### ISSUE TITLE
Could you add support for zipped OWL file loading

### ISSUE THREAD

**Issue by Robbie1977** [bio-ontology-research-group/aberowl-meta#7]
We have large OWL files (>100MB) and are looking at moving to gzip'd versions which is supported by several other ontology tools but you don't appear to currently support it?

A test example would be: https://github.com/VirtualFlyBrain/VFB_owl/raw/master/src/owl/vfb.owl.gz

**Comment by dosumis** [comment]
See see owlcs/owlapi#348 for discussion of OWL-API support for gzip.  Above URL is opened fine by Protege 5.

**Comment by Robbie1977** [comment]
Is this likely to happen?

**Comment by leechuck** [comment]
Done by https://github.com/bio-ontology-research-group/aberowl-obase/commit/4f4f5dad7899144ab4e799a6c3ad8c48aa690fbd

This will (for now) only work if you provide a URL, not when uploading the file directly.
